# Generated by Django 3.2 on 2021-05-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_language_settinglang'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[], default=0, max_length=6),
            preserve_default=False,
        ),
    ]
